import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import CustomAppBar from '@/components/Appbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>): JSX.Element {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <CustomAppBar />
        {children}
      </body>
    </html>
  );
}
